map_file = "MetaStation.dmm"
map_name = "MetaStation"
map_path = "map_files/MetaStation"
version = 1

[job_changes.Cook]
additional_cqc_areas = [
    "/area/station/service/bar",
    "/area/station/commons/lounge",
]

[shuttles]
cargo = "cargo_box"
emergency = "emergency_meta"
ferry = "ferry_fancy"
whiteship = "whiteship_meta"
