give_players_hooks = 1
map_file = "NebulaStation.dmm"
map_name = "NebulaStation"
map_path = "map_files/NebulaStation"
version = 1

[shuttles]
cargo = "cargo_nebula"
emergency = "emergency_nebula"
ferry = "ferry_nebula"
whiteship = "whiteship_tram"

[[traits]]
Linkage = "Cross"
Up = 1

[[traits]]
Baseturf = "/turf/open/openspace"
Down = 1
Linkage = "Cross"
